#!/bin/bash

# Help
if [ "$1" == "--help" ]; then
	echo "Help :"
	echo "------"
	echo pushpkg packageName
	exit 0
fi

# Check dependencies
if [ ! -f /usr/bin/mksrcinfo ]; then
	echo "pkgbuild-introspection not installed"
	echo
	./pushpkg --help
	exit 1
fi

# Check args
if [ "$1" == "" ]; then
	echo "No package selected"
	echo
	./pushpkg --help
	exit 1
fi

# Check package
if [ ! -d "$1" ]; then
	echo "Unknow package"
	echo
	./pushpkg --help
	exit 1
fi


# Extract pkgname
pkgname=$1
if [ "${pkgname: -1}" == "/" ]; then
	pkgname=${pkgname:0:${#pkgname}-1}
fi

# Confirm push
clear
read -p "Push ${pkgname} to AUR ? (y/N)" choice
case "$choice" in 
  y|Y ) echo "Begin push ${pkgname}...";;
  * )
    echo "Cancel push ${pkgname} !"
    exit 1
  ;;
esac

# Init
rm -Rf .tmp 2> /dev/null
mkdir .tmp
cd .tmp
git clone ssh://aur@aur.archlinux.org/${pkgname}.git
if [ ! "$?" = "0" ]; then
	cd ..
	rm -Rf .tmp
	echo ""
	echo ""
  echo "No AUR ssh key loaded exiting..."
  exit 1
fi

# Prepare
cd ${pkgname}
git rm *
cp ../../${pkgname}/* .
mksrcinfo
git add .SRCINFO *
git commit -m "New version" .SRCINFO *

# Push
git push

# Clean
cd ../..
rm -Rf .tmp
